import GridItem from "./GridItem";
import styles from "@/app/welcome/welcome.module.css";

export default function GridSection(){
    return(
        <div className={styles.gridSection}>
            <GridItem title={"Tell us what you’ve seen"} img={"https://media.formula1.com/image/upload/t_16by9North/c_lfill,w_3392/q_auto/v1740000000/trackside-images/2025/F1_Grand_Prix_Of_China___Previews/2205973441.webp"}
                    text={"Get your Letterboxd underway by visiting our Popular section and marking a few races you’ve seen. Click the ‘eye’ on any race poster to tell us you’ve watched it (add a ‘like’ if you liked it and/or a rating). We add all watched races to your races tab and then we can show you reviews and other cool stuff."}/>
            <GridItem title={"Browse your watched races"} img={"https://media.formula1.com/image/upload/t_16by9North/c_lfill,w_3392/q_auto/v1740000000/trackside-images/2025/F1_Grand_Prix_Of_China___Previews/2205973441.webp"}
                    text={"Now that you’ve added some races, you can find them in the races tab of your profile.\nAs you add more content, your profile starts to reflect your taste.\nYou can also browse the races of other members, or the community, with Hide watched races activated to find more great races to watch."}/>
            <GridItem title={"Save races to watch later"} img={"https://media.formula1.com/image/upload/t_16by9North/c_lfill,w_3392/q_auto/v1740000000/trackside-images/2025/F1_Grand_Prix_Of_China___Previews/2205973441.webp"}
                    text={"One of our most-loved features, the Watchlist, lets you keep a list of races you want to see.\nStart in Most Anticipated and mark a few races you want to see—use the ‘clock’ on a race or review page, or open the options menu on any poster (shown opposite).\nIf you subsequently log or mark a race as watched, we’ll move it from your Watchlist to your races (and add it to your Diary, if you provide a date—more on that below)."}/>
            <GridItem title={"Your account, profile and settings"} img={"https://media.formula1.com/image/upload/t_16by9North/c_lfill,w_3392/q_auto/v1740000000/trackside-images/2025/F1_Grand_Prix_Of_China___Previews/2205973441.webp"}
                    text={"Click your username (at the top of each page) for shortcuts to the main sections of your account. Your Profile, races, Diary, Watchlist and other pages are here.\nYou can customize your name, location, website, bio and favorite races in Settings. We use your X / Twitter avatar if you connect your account, or a Gravatar matching the email on your profile.\nNote: your profile (and any other content you publish, with the exception of private lists) is visible to others, and to search engines."}/>
            <GridItem title={"Log a race"} img={"https://media.formula1.com/image/upload/t_16by9North/c_lfill,w_3392/q_auto/v1740000000/trackside-images/2025/F1_Grand_Prix_Of_China___Previews/2205973441.webp"}
                    text={"Log a race to tell us you watched it on a particular date, and to attach a review, rating and tags.\nWe put all races you log with a date into your Diary, a great reference for when it comes time to compile your year-end list. You can rate races without logging them too, either on a race or review page, or from the ‘more options’ menu on a poster.\nTry logging a race now…"}/>
            <GridItem title={"Following and activity"} img={"https://media.formula1.com/image/upload/t_16by9North/c_lfill,w_3392/q_auto/v1740000000/trackside-images/2025/F1_Grand_Prix_Of_China___Previews/2205973441.webp"}
                    text={"The best way to find members to follow is by reading reviews of races you like, to identify the voices and opinions you dig. Our Members page lists popular accounts.\nAs you follow more people, we create a personalized Activity stream full of reviews and recommendations from these members (and you’re bound to find new people to follow from the Likes included here).\nUse the Incoming tab to see who’s interacting with you, and upgrade to Pro to personalize the types of activity you see on each device."}/>
            <GridItem title={"Make and share lists"} img={"https://media.formula1.com/image/upload/t_16by9North/c_lfill,w_3392/q_auto/v1740000000/trackside-images/2025/F1_Grand_Prix_Of_China___Previews/2205973441.webp"}
                    text={"Lists are a great way to share a collection of related races, or to rank the races of your favorite track, driver, or season.\nIt’s fun to welcome suggestions for your lists from other members. Start a list on your Lists tab, then add races on the ‘Edit’ screen (or from the ‘more options’ menu on a poster).\nThe first time you make a list public, it’s shared with your followers."}/>
        </div>
    )
}